services:
  allhands22:
    image: "${TESTING_IMAGE}"
  
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./healthchecks:/healthchecks
    healthcheck:
      #test: /healthchecks/postgres-healthcheck
      test: ["CMD-SHELL", "pg_isready"]
      interval: "5s"
  sut:
    image: "${TESTING_IMAGE}"
    depends_on:
      allhands22:
        condition: service_started
      postgres:
        condition: service_healthy
    # run all your tests here against the allhands22 service
    command: curl --fail http://allhands22:80 || exit 1